### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by memyselkf** [Mzzzj/CS2_DMA_Extrnal#12]
当我在构建 Progarm 后启动它时，它说
Assertion failed: IsObject(), file C:\Users\Admin\source\repos\CS2_DMA_Extrnal\CS2_External\includes\rapidjson\document.h, line 1154
如何修复?

**Comment by 2063669460** [comment]
添加offsests和clind到exe的目录

**Comment by Mzzzj** [comment]
[加discord](https://discord.gg/4jVeaApzdX) 可以免费用非开源版
