### ISSUE TITLE
Getting message:1

### ISSUE THREAD

**Issue by ProbablyXS** [Mzzzj/CS2_DMA_Extrnal#16]
I want to use the parameter 1 for showing from moonlight screen but i receive the message:1 every 3 secondes

How i can fix this problem thx you very much in first

**Comment by Mzzzj** [comment]
Open the game

**Comment by Mzzzj** [comment]
Different versions of Moonlight windowName and class are different. Use Winspy to view the window name and class name of Moonlight 
`CS2_DMA_External_Remastered.exe en CodeKey 2 Moonlight SDL_app 9 115200
`
my Moonlight  versions is 4.3.1，  You can also use this version Moonlight

**Comment by ProbablyXS** [comment]
Alright thx for your fast response i have see on your real launcher (used with webview2) need to have moonlight version 4.3.1

Have nice day ❤
