### ISSUE TITLE
编译版本出现方框错误显示，包括aimbot也不可用，请问编译版本有这个问题吗，还是说我的问题。。

### ISSUE THREAD

**Issue by IDhammaI** [Mzzzj/CS2_DMA_Extrnal#18]
![72f8e952adbd2d92e07f8cb47b0249c](https://github.com/Mzzzj/CS2_DMA_Extrnal/assets/124808841/331e7366-86c5-452c-a7cd-ef94fd29fe47)

**Comment by subeoy1** [comment]
版本已经过时了。

**Comment by ywl123456** [comment]
怎么更新 现在就是这个错误

**Comment by IDhammaI** [comment]
有偿解决&nbsp;


1518470138
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月31日(星期三) 下午2:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Mzzzj/CS2_DMA_Extrnal] 编译版本出现方框错误显示，包括aimbot也不可用，请问编译版本有这个问题吗，还是说我的问题。。 (Issue #18)














 
怎么更新 现在就是这个错误

**Comment by huafengtc** [comment]
解决了吗？我更新了偏移数据也依然不可用

**Comment by IDhammaI** [comment]
解决了&nbsp;


1518470138
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年8月14日(星期三) 中午11:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Mzzzj/CS2_DMA_Extrnal] 编译版本出现方框错误显示，包括aimbot也不可用，请问编译版本有这个问题吗，还是说我的问题。。 (Issue #18)














 
解决了吗？我更新了偏移数据也依然不可用

**Comment by huafengtc** [comment]
> 解决了&nbsp; 1518470138 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年8月14日(星期三) 中午11:42 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [Mzzzj/CS2_DMA_Extrnal] 编译版本出现方框错误显示，包括aimbot也不可用，请问编译版本有这个问题吗，还是说我的问题。。 (Issue #18) 解决了吗？我更新了偏移数据也依然不可用 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

可以分享一下吗？

**Comment by ywl123456** [comment]
估计是不行 他是有偿解决

**Comment by IDhammaI** [comment]
我已经解决了，你们可以找我咨询解决，谁的时间也是时间lol

**Comment by IDhammaI** [comment]
有偿
&nbsp;


1518470138
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年8月14日(星期三) 中午1:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Mzzzj/CS2_DMA_Extrnal] 编译版本出现方框错误显示，包括aimbot也不可用，请问编译版本有这个问题吗，还是说我的问题。。 (Issue #18)














  
解决了&nbsp; 1518470138 @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2024年8月14日(星期三) 中午11:42 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [Mzzzj/CS2_DMA_Extrnal] 编译版本出现方框错误显示，包括aimbot也不可用，请问编译版本有这个问题吗，还是说我的问题。。 (Issue #18) 解决了吗？我更新了偏移数据也依然不可用 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
可以分享一下吗？

**Comment by huafengtc** [comment]
明白明白。

**Comment by ywl123456** [comment]
怎么加

**Comment by IDhammaI** [comment]
1518470138 q
&nbsp;


1518470138
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年8月14日(星期三) 中午1:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Mzzzj/CS2_DMA_Extrnal] 编译版本出现方框错误显示，包括aimbot也不可用，请问编译版本有这个问题吗，还是说我的问题。。 (Issue #18)














 
怎么加
