### ISSUE TITLE
[Error] Failed to attach process, StatusCode:1

### ISSUE THREAD

**Issue by xCorteX** [Mzzzj/CS2_DMA_Extrnal#2]
![image](https://github.com/Mzzzj/CS2_DMA_Extrnal/assets/37551164/4a1de68c-9519-4d28-9671-c0ac406511b0)

how to fix this ?

directory looks like this
![image](https://github.com/Mzzzj/CS2_DMA_Extrnal/assets/37551164/23321b5a-0b66-46e8-bef3-282beccc5a13)
do I missing something?

**Comment by Mzzzj** [comment]
Start the game first

**Comment by xCorteX** [comment]
the Game is Running 
and yes the DMA card is Working 

what could be the problem?

**Comment by Mzzzj** [comment]
update offset file

**Comment by yahur** [comment]
@xCorteX can you add my discord? I am in need of help and am lost, 10 hours of research still stuck please help disc : nicezke

**Comment by xCorteX** [comment]
> update offset file

Offset is updated…
