### ISSUE TITLE
Aimbot isn't

### ISSUE THREAD

**Issue by akumareutre** [Mzzzj/CS2_DMA_Extrnal#5]
Hi man,
I have a problem, when I launch the cheat with selection 3 the menu opens the esp works very well the radar too but not the aimbot/trigger bot/others

![1](https://github.com/Mzzzj/CS2_DMA_Extrnal/assets/66709857/005de1f1-1a88-46ca-a26f-281421f3058d)

**Comment by Mzzzj** [comment]
viewAngle offset need update

**Comment by akumareutre** [comment]
OK oK, this is a manipulation that I can do alone if so how could I do it or it is a file that we should expect from your github repos ?
