### ISSUE TITLE
更新出现问题

### ISSUE THREAD

**Issue by Sock-Business** [Mzzzj/CS2_DMA_Extrnal#9]
我已经替换目录中两个json文件 
1.client.dll.json
2.offsets.json

此两个文件我都替换了 但是进入游戏还是没有效果

**Comment by Sock-Business** [comment]
已经解决原来需要把json文件放到程序下

**Comment by lum0022** [comment]
能发我一份吗，1289340213@qq.com

**Comment by xiaticc1** [comment]
能发我一份吗 elxat200435@qq.com

**Comment by Leezren** [comment]
> 我已经替换目录中两个json文件 1.client.dll.json 2.offsets.json
> 
> 此两个文件我都替换了 但是进入游戏还是没有效果

现在好像又不行了 有没有办法更新？

**Comment by Accel1337** [comment]
现在还能正常使用吗
